
version: '2'

services:
  db:
    image: wof_postgis
    volumes:
      - ../postgres_data:/var/lib/postgresql/data    
    tmpfs:
     - /tmp
    environment:
     - POSTGRES_DB=whosonfirst
     - POSTGRES_USER=whosonfirst
     - POSTGRES_PASSWORD=whosonfirst 


  wof_wiki_dw:
    image: wof_wiki_dw
    volumes:
     - ../whosonfirst-data:/wof/whosonfirst-data
     - ../wikidata_dump:/wof/wikidata_dump
     - ../natural-earth-vector:/wof/natural-earth-vector
     - ../geonames:/wof/geonames
     - ./code:/wof/code
     - /var/www/html/wof-wiki-dw/output:/wof/output     
    links:
     - db:db
    environment:
     - PGHOST=db         
     - PGUSER=whosonfirst
     - PGDATABASE=whosonfirst
     - PGPASSWORD=whosonfirst
     - DB_HOST=db         
     - DB_USER=whosonfirst
     - DB_NAME=whosonfirst
     - DB_PASS=whosonfirst

